In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
%matplotlib inline 

In [2]:
df = pd.read_csv("spam.csv")

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.describe()

Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [5]:
df.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [6]:
from sklearn.preprocessing import LabelEncoder 
encoder = LabelEncoder()
df["Category"]=encoder.fit_transform(df["Category"])

In [7]:
df.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [8]:
df["Category"].describe()

count    5572.000000
mean        0.134063
std         0.340751
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: Category, dtype: float64

In [9]:
df["Category"].value_counts()

0    4825
1     747
Name: Category, dtype: int64

In [10]:
#0---> ham
#1-->spam

In [11]:
#another approach
#df["spam"] = df["Category"].apply(lambda return x:1 if x == "spam" else 0)

In [12]:
X = df["Message"]
y = df["Category"]

In [13]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [14]:
#CountVectorizer Tutorial
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    "This is a Cat",
    "I love my dog",
    "This is NLP programming", 
    "We will we will rock you"
]
vector = CountVectorizer()
X = vector.fit_transform(corpus)
print(vector.get_feature_names_out())
print(X.toarray())

['cat' 'dog' 'is' 'love' 'my' 'nlp' 'programming' 'rock' 'this' 'we'
 'will' 'you']
[[1 0 1 0 0 0 0 0 1 0 0 0]
 [0 1 0 1 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 2 2 1]]


In [15]:
X_train.values

array(['Package all your programs well',
       'Sunshine Quiz Wkly Q! Win a top Sony DVD player if u know which country the Algarve is in? Txt ansr to 82277. £1.50 SP:Tyrone',
       'Good evening Sir, Al Salam Wahleykkum.sharing a happy news.By the grace of God, i got an offer from Tayseer,TISSCO and i joined.Hope you are fine.Inshah Allah,meet you sometime.Rakhesh,visitor from India.',
       ...,
       'Wen ur lovable bcums angry wid u, dnt take it seriously.. Coz being angry is d most childish n true way of showing deep affection, care n luv!.. kettoda manda... Have nice day da.',
       'Ü dun wan to watch infernal affair?',
       'RGENT! This is the 2nd attempt to contact U!U have WON £1250 CALL 09071512433 b4 050703 T&CsBCM4235WC1N3XX. callcost 150ppm mobilesvary. max£7. 50'],
      dtype=object)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer 
vectorizer = CountVectorizer()
X_train_count = vectorizer.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
from sklearn.naive_bayes import MultinomialNB 
mNB = MultinomialNB()
mNB.fit(X_train_count, y_train)

MultinomialNB()

In [18]:
emails = ["Hey Mustakim, can we get together to watch footbal game tomorrow?",
        "Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!"]
emails_counts = vectorizer.transform(emails)
mNB.predict(emails_counts) 

array([0, 1])

In [24]:
from sklearn.metrics import accuracy_score
X_test_count = vectorizer.transform(X_test)
#mNB.score(X_test_count, y_test)
predictions = mNB.predict(X_test_count)
print(predictions) 
print(accuracy_score(y_test, predictions)) 

[0 0 0 ... 0 0 0]
0.9863603732950467


In [26]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("mNB", MultinomialNB())
])

In [28]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('mNB', MultinomialNB())])

In [29]:
pipeline.score(X_test, y_test) 

0.9863603732950467

In [30]:
pipeline.predict(emails)

array([0, 1])